- profiles/updates/1Q-2019
neither libmed nor med-fichier are in the overlay anymore and the move
brings trouble on depcleans with freecad depending on med-fichier which
isn't existing at all.
> profiles: drop updates/1Q-2019

- media-libs/opencamlib/metadata.xml
- media-libs/opencamlib/opencamlib-9999.ebuild
If present on the system freecad supports this out of the box.
Package-Manager: Portage-2.3.67, Repoman-2.3.14
> media-libs/opencamlib: new package

- sci-libs/opencascade/opencascade-7.3.0.ebuild
Ensure no error is thrown, if the directory doesn't exist.
Package-Manager: Portage-2.3.67, Repoman-2.3.15
> sci-libs/opencascade: re-add -f flag to rm

- media-gfx/freecad/freecad-0.18.2-r1.ebuild
- media-gfx/freecad/freecad-9999.ebuild
- media-gfx/freecad/metadata.xml
Sync with changes from 0.18.2
Add mpi USE flag and propagate it to dependencies
Change ${S} to point to correct path for both, versioned and live ebuild
Only install docs, for versioned ebuilds
> media-gfx/freecad-9999: fixes for issue #120

- media-libs/draco/draco-1.3.5-r1.ebuild
- media-libs/draco/metadata.xml
* add compat and gltf USE flags
Package-Manager: Portage-2.3.71, Repoman-2.3.17
> media-libs/draco: improve ebuild

- media-gfx/freecad/freecad-0.18.3.ebuild
- media-gfx/freecad/freecad-9999.ebuild
- dev-python/git-python can be used in case of urllib for Addon Manager (i.e. USE=addonmgr), so we add this as a runtime dependency, when this USE flag is set
- sync live ebuild with versioned ebuild
Thanks to Thomas Scheiblauer for pointing this out.
Suggested-by: Thomas Scheiblauer <tom@sharkbay.at>
Package-Manager: Portage-2.3.71, Repoman-2.3.17
> media-gfx/freecad: add RDEPEND for git-python

- media-gfx/freecad/freecad-0.18.3.ebuild
Enable the BUILD_TEST option by default, to build the runtime test module
of FreeCAD.
Package-Manager: Portage-2.3.73, Repoman-2.3.17
> media-gfx/freecad: enable test by default

- sci-libs/vtk/vtk-8.2.0.ebuild
On a test, I noticed that dev-libs/double-conversion and dev-db/sqlite
are needed for default configuration (+X). The missing dependencies
are added in this patch.
Package-Manager: Portage-2.3.75, Repoman-2.3.17
> sci-libs/vtk: add missing deps

- media-gfx/freecad/freecad-0.18.3.ebuild
- media-gfx/freecad/freecad-9999.ebuild
The patch fixes the mpi USE flag for sci-libs/med, which has been dropped
by the merge of libmed with med. As the USE flag will possibly come back
in the future, the patch uses mpi(+)? syntax.
Also removing fortran USE dependency from med. This actually isn't used by
freecad, it only links to the C library.
Closes: https://github.com/waebbl/waebbl-gentoo/issues/141
Package-Manager: Portage-2.3.76, Repoman-2.3.17
> media-gfx/freecad: fix mpi USE flag

- media-gfx/freecad/freecad-9999.ebuild
Due to upstream changes, the src_install function had to be changed. The
installation is now a lot cleaner.
Thanks to @Petross404 for pointing this out.
Closes: https://github.com/waebbl/waebbl-gentoo/issues/149
Reported-by: Petros S <petros404@gmail.com>
Package-Manager: Portage-2.3.76, Repoman-2.3.17
> media-gfx/freecad: fix install issues

- dev-python/shiboken/files/shiboken-5.11.1-include-QStringList.patch
- dev-python/shiboken/shiboken-5.11.1.ebuild
- Fix an issue where QStringList was not found.
- Update copyright year
- Modify to use new cmake.eclass
> dev-python/shiboken: fix an #include directive issue

- media-libs/coin/coin-4.0.0a_pre20181221.ebuild
- update copyright year
- use new cmake eclass
> media-libs/coin: update to use cmake.eclass

- media-gfx/freecad/freecad-0.18.3.ebuild
- update of copyright year
- use new cmake.eclass
> media-gfx/freecad: update to use cmake.eclass

- media-gfx/freecad/freecad-0.18.3.ebuild
- media-gfx/freecad/freecad-9999.ebuild
This makes the freecad ebuild work with media-libs/coin-4.0.0a_pre20191109 from the main gentoo repository.
> media-gfx/freecad: work with gentoo repo media-libs/coin-4.0.0a*

- media-gfx/freecad/files/freecad-9999-0001-Gentoo-specific-disable-building-assembly-workbench.patch
- media-gfx/freecad/freecad-9999.ebuild
Add a patch to disable building the assembly workbench for
Gentoo builds.
> media-gfx/freecad: add patch to disable assembly

- media-libs/SoQt/SoQt-1.6.0.ebuild
- enable changes in src_prepare and src_install from 1.6.0a_pre* version
- change default CMAKE_INSTALL_INCLUDEDIR to be coherent with coin-4.0.0
> media-libs/SoQt: fix some issues

- media-gfx/freecad/freecad-0.18.4.ebuild
- add libspnav[X]
- add coin[vrml97(+)], also change coin[simage] to coin[simage(+)]
because the USE flag is not available in main tree coin
> media-gfx/freecad: fix previous commit

- profiles/package.use.mask
- sci-libs/vtk/metadata.xml
- sci-libs/vtk/vtk-8.2.0.ebuild
- remove dependencies on sci-libs/proj and sci-libs/xkaapi, the latter to stay in sync with Gentoo version
- remove support for python 3.{7,8} again. They lead to many fatal errors with repoman, due to some dependencies on a few arches don't support them.
- also add masks for python 3.{7,8} to profiles/package.use.mask
> sci-libs/vtk: fix dependency issues

- media-gfx/freecad/files/freecad-0.18.4-0004-fix-std-namespace-issues.patch
- media-gfx/freecad/freecad-0.18.4.ebuild
- use dev-util category, until Gentoo dev-python/pybind11 provides
cmake config files.
- temporarily remove python 3.7 support, because some dependencies don't
support it yet.
- fix several issues with missing std:: namespace
Package-Manager: Portage-2.3.86, Repoman-2.3.20
> media-gfx/freecad: switch pybind11 category

- media-gfx/freecad/freecad-0.18.4-r1.ebuild
- media-gfx/freecad/freecad-9999.ebuild
Only apply generator patch for >=dev-python/pyside2-tools-5.14.0.
Thanks to @CaptainBloodz for reporting the issue.
Also apply a patch to enable freecad to build against opencascade-7.3.0
as well as opencascade-7.4.0, due to library install path changes between
the two versions.
Thanks to @robert7k for bringing this to my attention.
Reported-by: @CaptainBloodz
Reported-by: @robert7k
Closes: https://github.com/waebbl/waebbl-gentoo/issues/194
Package-Manager: Portage-2.3.89, Repoman-2.3.20
> media-gfx/freecad: add <Qt-5.14 compatibility

- media-gfx/freecad/freecad-9999.ebuild
For Gentoo, FreeCAD needs to depend on pyside2-5.14 and
qt-5.14 to properly handle and compile some python scripts
using /usr/bin/{rcc,uic}.
Reported-by: Michal Ulianko (@Grawp)
Closes: https://github.com/waebbl/waebbl-gentoo/issues/203
Package-Manager: Portage-2.3.89, Repoman-2.3.20
> media-gfx/freecad: fix rcc/uic issue

- media-gfx/freecad/freecad-0.18.4-r1.ebuild
- profiles/package.use.mask
- sci-libs/vtk/vtk-8.2.0-r2.ebuild
VTK and freecad build and run successfully with python 3.7, all dependencies are available.
> freecad/vtk: enable python3_7

- media-libs/quarter/quarter-1.1.0.ebuild
The `Quarter.pc.cmake.in` has a hardcoded libdir path. This fixes it by using a bit of sed and get_libdir. Ran into this while building FreeCAD.
> media-libs/quarter: fix libdir in Quarter.pc file

- media-gfx/freecad/freecad-0.18.4-r1.ebuild
- media-gfx/freecad/freecad-9999.ebuild
the current logic fails as it does not take the revisions into account.
Only one version of opencascade remains in the main tree and this one
uses the correct libdir. This fixes https://github.com/waebbl/waebbl-gentoo/issues/228
> media-gfx/freecad: always use get_libdir for opencascade

- media-gfx/freecad/freecad-9999.ebuild
The missing includes are now in the FreeCAD github code, so this patch is no longer necessary. Without this, it builds OK, and based on limited testing seems to work properly.
> Removed obsolete patch

- media-gfx/freecad/files/freecad-0.18.4-0007-fix-boost-placeholders-problem.patch
- media-gfx/freecad/freecad-0.18.4-r1.ebuild
Thanks to Huang Rui (@vowstar) for reporting the issue and providing
a patch.
Reported-by: Huang Rui <vowstar@gmail.com>
Closes: https://github.com/waebbl/waebbl-gentoo/issues/250
Package-Manager: Portage-3.0.5, Repoman-3.0.1
> media-gfx/freecad: fix boost placeholders issue

- media-gfx/freecad/files/freecad-9999-0001-Gentoo-specific-disable-building-assembly-workbench.patch
The patch fixes an issue where the complete workbench has been
set to default OFF, while the
${P}-0001-Gentoo-specific-disable-building-assembly-workbench.patch
has still set it to ON.
Reported-by: Miroslav Šulc <fordfrog@gentoo.org>
Closes: https://github.com/waebbl/waebbl-gentoo/issues/255
Package-Manager: Portage-3.0.8, Repoman-3.0.1
> media-gfx/freecad: update for upstream changes

- sci-mathematics/netgen/netgen-6.2.1910.ebuild
change dependency for obsolete virtual/ffmpeg
Package-Manager: Portage-3.0.8, Repoman-3.0.2
> sci-mathematics/netgen: fix dependency

- media-gfx/freecad/freecad-0.18.5-r2.ebuild
- media-gfx/freecad/freecad-9999.ebuild
- Fix an issue with opencascade, where the oce libraries will
be linked, if both, sci-libs/opencascade and sci-libs/oce
are installed.
- Fix the exec line of the desktop file to use the lower case
symlink.
Thanks to @chl-repo for pointing out the desktop file issue.
> media-gfx/freecad: small fixes

- sci-libs/vtk/vtk-8.2.0-r2.ebuild
Build fails with current stable pugixml-1.10
Reported-by: @RayOfLight1
Closes: https://github.com/waebbl/waebbl-gentoo/issues/277
> sci-libs/vtk: fix pugixml dependency

- media-gfx/freecad/freecad-0.18.5-r2.ebuild
- media-gfx/freecad/freecad-9999.ebuild
The package dev-python/pyside2-tools is no longer needed, as the standard `uic` and `rcc` tools from Qt5 are supporting generation of python files, from `.ui` or `.rc` files, respectively.
> media-gfx/freecad: remove pyside2 tools

- .travis.yml
Use python-3.8 and portage-3.0.12
> .travis.yml: update versions

- metadata/layout.conf
Remove raiagent overlay from masters, it's not needed anymore
due to pyside2-tools being in ::gentoo now.
> metadata/layout.conf: update masters

- .travis.yml
Remove the -i (--ignore-arches) option
> .travis.yml: remove option

- media-gfx/freecad/freecad-0.18.5-r2.ebuild
- Restrict to <vtk-9
Thanks to @vowstar
Reported-by: Huang Rui (@vowstar)
Closes: https://github.com/waebbl/waebbl-gentoo/issues/287
Bug: https://github.com/waebbl/waebbl-gentoo/issues/288
> media-gfx/freecad: update to C++14

- dev-libs/imath/files/imath-9999-0001-fix-link-file-name-for-libPyImath_Python.patch
- dev-libs/imath/imath-9999.ebuild
- dev-libs/imath/metadata.xml
- media-libs/openexr/metadata.xml
- media-libs/openexr/openexr-9999.ebuild
media-libs/openexr: add live package
Features the upcoming release 3 of openexr.
Revdep compatibility with <openexr-3 not tested!
Package-Manager: Portage-3.0.16, Repoman-3.0.2
dev-libs/imath: new package (live)
Successor package for the {,Py}Imath parts of
media-libs/ilmbase and dev-python/pyilmbase. The other
other {,py}ilmbase libraries are part of media-libs/openexr.
Package-Manager: Portage-3.0.14, Repoman-3.0.2
In preparation for upcoming openexr-3.
Not for use in production yet! Check revdeps.
> openexr-3 packages

- sci-libs/calculix-ccx/calculix-ccx-2.10.ebuild
Fixing https://github.com/waebbl/waebbl-gentoo/issues/307
> sci-libs/calculix-ccx: fix compilation with gcc-10

- media-gfx/freecad/files/freecad-0.19.1-0001-Gentoo-specific-Remove-ccache-usage.patch
- media-gfx/freecad/files/freecad-0.19_pre20201231-0003-Gentoo-specific-don-t-check-vcs.patch
- media-gfx/freecad/freecad-9999.ebuild
Add some guards to select the correct options,
based on the version of sci-libs/opencascade that is
installed and eselected.
Closes: https://github.com/waebbl/waebbl-gentoo/issues/313
Package-Manager: Portage-3.0.18, Repoman-3.0.3
> media-gfx/freecad: fix opencascade issues

- media-gfx/freecad/files/99freecad
The env file has been forgotten in the latest update
to the live ebuild.
Thanks Jan for reporting this quickly!
Package-Manager: Portage-3.0.18, Repoman-3.0.3
> media-gfx/freecad: add env file

- .github/workflows/pkgcheck.yml
- .github/workflows/repoman.yml
update repoman.yml:
Use portage from git master branch, not versioned package
Get latest repoman version from git and checkout that version
update pkgcheck.yml:
Use pkgcheck-action from pkgcore.
Keywords borrowed from ::science, not yet adapted
> .github/workflows: try to fix github actions files

- .github/workflows/pkgcheck.yml
One the keywords passed, was wrong VisibleVcsPackage -> VisibleVcsPkg
> github-actions: fix error in pkgcheck.yml

- sci-libs/calculix-ccx/calculix-ccx-2.17-r1.ebuild
- sci-libs/calculix-ccx/metadata.xml
The arpack package is no longer optional.
Closes: https://github.com/waebbl/waebbl-gentoo/issues/335
Package-Manager: Portage-3.0.20, Repoman-3.0.3
> sci-libs/calculix-ccx: drop USE=arpack

- media-libs/openexr/openexr-9999.ebuild
Sync KEYWORDS with stable 3.1.4
> media-libs/openexr: unslot slot 3

- media-gfx/netgen/netgen-6.2.2204.ebuild
The libtogl.a library is referenced in netgen-targets.cmake.
> media-gfx/netgen: keep the libtogl.a libary

- dev-cpp/zipios/files/zipios-9999-fix-doc-installation-dir.patch
- dev-cpp/zipios/files/zipios-9999-use-catch2-name-instead-of-snapcatch2.patch
- dev-cpp/zipios/zipios-9999.ebuild
- drop tests for this version for now
> dev-cpp/zipios: add live ebuild (9999)
